### ISSUE TITLE
Exports broken on Firefox

### ISSUE THREAD

**Issue by w-biggs** [3rd/tsdiagram#12]
The default diagram, when exported, is a broken mess on Firefox. It looks like the issue is the export, not the SVG rendering; the same exported diagram is also broken when loaded into Chrome.

![image](https://github.com/3rd/tsdiagram/assets/3406010/3cdc7828-7b9b-47fd-bf6c-0199c52b0d5f)
![diagram](https://github.com/3rd/tsdiagram/assets/3406010/2cde71db-aa7e-42e3-ace5-69ea6cc27a97)

**Comment by 3rd** [comment]
Added a hack to semi-fix it on Firefox, the browser itself seems to have some rendering issues and renders things exactly as you can see them in your image initially, then it fixes itself somehow. Looks like a Firefox problem.
Added a small delay to let it do its thing, but it's just a hack, I'd expect other rendering issues.
