### ISSUE TITLE
Optional properties in classes dont appear

### ISSUE THREAD

**Issue by thomaslule** [3rd/tsdiagram#14]
Hello,

It would be nice if optional properties in classes were displayed in the same way as optional properties in interfaces:

https://tsdiagram.com/#/N4IgJg9gxgrgtgUwHYBcDOIBcBtUBLMLcBAMwEMYAbFEAGhBTxUoSIHUFKoJE6Q0IMAE5RWmEHlQIh5UQAIAsgE8AklJll5wADpI5ciAAdGEJGUoB+THLQohkgOa6AvgG5duqJTJo0ipQDC3r5yOnoGxnim5lY2do4uunzBKAoQYHgkeAiEmACMAOwATAAMJQAceSUAzABsACwArOXOALr0sEJCyCgAItDwPSq5xORUNM5AA

**Comment by 3rd** [comment]
Hey, added now, thank you!
