### ISSUE TITLE
Crash on invalid selector

### ISSUE THREAD

**Issue by joelsoedito** [3rd/tsdiagram#18]
I was trying out TSdiagram and while making a typo the app crashed and I'm unable to rewind. I probably typed an invalid character, but since it was a type im unsure which character. Whenever I reload the page it will go back to the scheme and reproduce the same error. 

This is the [URL](https://tsdiagram.com/#/N4IgJg9gxgrgtgUwHYBcDOIBcBtUBLMLEARjAAUB2AMwFliBaegfQDcAbAIwAYW8BlAIIAlYkxAAaECjwo2CIjQQAnKAEMUEAAQ1VS1UgRs2ECSDQQYK+ZhAB6W5rQrbAB1UBPY6rCuPXsPQo7i4IaAB06AA6SNH2mjBoymjReKjKVKpQCJoAqolKmsDRmpoEmI4oSqkA5gDcxZouShBUeHIAkmDlaJU19UglCHCqbd29SHWaccbVqZpDI2wNbmhoAO4QSl0VVRP9JT1VIQDCCRqISp0A-GO7dQ3NcmjlkSAcMO7Kr5oAPpqviSMXxAv3+IG8cFS3z+rwQYBkm1e+0azVaHSQVAg5TIqLaCGRlX0aDU0ggSGemgAKnpyZlSUhsABdZGZKAWVA4hBUZTILIUgRQNkwDlKLk8pB85FsPA9GoUgAyMukEyZyLQMA4xKO9IpfA1WrwLnpyKgovUcIEKHKABFzciYC4wOawJabXbogBfaKxBzHMkoOmlDGbYb0zRwCBgQwpNJKDJZTQ4lp4woNMo7PoNVpKHoAOVUiFumYGmjYqjzBYQRb2DTZcDcSHc+cQNwzNZLqhY6l05UU8NUyI4+gMl2G1Sr2jheAHDQ4eCxbfuHbAYFFq2rS5KUBk7g3aoDKAnh2LJQAXoa-VG98sABZkhCt497KYOADyRvnSFUbEad4MmneFBNFFABHGA8FFMB5mGNorgaBZYL3F8gzURJNDZVBAxlTR4SoblRVQTQUBvfRSwgWYYiQL1KNSQ840ybIBSFEUxQIvlUxLUUsjwFgEB0JQAGsEGVaoAFEYLYCkOAgCA5H0NVOzhPgEF0KAb1CDdVWQnR3A4bICDQTRNk0IT3A2LZDMxAo0EUqDElU9Tkio70kDiakiTpT9w0jQxNAACjwKhNAMOE4U0KzGg8RBUEM4yXDLAZ1U1U1DR1ABKaIEAADxcTYgKCEIqRpGyoDDABeDiSnTJ9N3ifJyjyZRkXi-ROmvDsI2FK1gvgPSlAJYrPLJW1DzdQ9kVSFgIDwLJynaJAppm-FkMhaobyAvTNBIpAwDkKCOHcTQ+F6EIGh6dQEnKAByOt4uEuErtBK6Qh2mpHr+K6MjxMArv6D1+hjOj42yebFoTIoS2q8ZJjiHIkDwMD9KjVBArwZRwuM4j9IW6asgaBJlDaxdamQoRWN5bINCI9TcnyeYUaCM6ToQUHcZZ7YapJuJjqOEGcaWzR2mtBoC3ZFAyBGbYkF6prkIETrCLcAgg3Q5AohLWAlDY3dieQ04td5Q62SjfyEDCaownEMEcj4YWQAykslZdbqRuWuJXep7GweyNZy0ighazNQ9nbG-F8cdZ1XU0V2-pc2j0gYo79RSj8yUq0oOehrmHDhhGYCRtXUfRiKsccZPtU-fH8iJznSfJiVKa0UvGoKQvGZLY8TjOCALhrrPkJ5w1slOHoe-RoWmd5vVkorsk+7ubOjuZpOZ9SryJ8dhLsQSuv8Ipoim5psgd7b9wmYuilXk83joTBVJr4QW-XjUBu9qRc+lBQV3Q+RZAwG-6O5pQTSyMIvXMMAjClCCmSao00JiBxUsHKOMdw5OiQS7d0zkaKxmBomHeEMqqZwXshXOiMM6F1aMXTGNMWqURKF+Qsus4jH1Igw7IfkzYWytq8AAQuWGarxuEgE5JCeArwHYHGZiwpA88+h602GuXKr0JhL15ng0iG8ShNCWuUaWcA+qLxxALOYWQYq1ksNrJCcR9ba3Qj5U25tLbW1tuItMsYuxsBeCACMqAbxPxAJ8XQSJkI8LaNKFR8clAeKzIgywGlFxaTiIqHoRkgrcgumuTQnZFiqA4HIFWxFsK0IQZHDB41UGlJ-p6FycRICEQEkgCAawoGlEgQTamMpAYJwTBLdw0UUCKGIpGdOUNiGw3hmQggFC0YFBLjQqKatwzCTvGAKuhMiFyLiGTPeDcD6e1pujU+k8h69P6YMlZsjnzc2XqcxZ5zhmaPQroMAPCaQbKub6Z5AE3kOK4WCAAajKVQgiwQ6B6MoY4zzXEljLD0AALFYhw8pyxAThThPAsx0CpP2WoLY8Eco0H9DeXRMt+rIVEjlCC6gvI+OIvilwABNFSSgSX6NlnEClLgqVhkCUoEp6CqklgdGgi0ZSw5YMyjlPKQYgaJz7NOEZ7zarfm6pzWsqhU5IFbEIGaN5KTZRQEyYBEC2D2iUGwR80NjWgKzHiNhlq7jWtNQ0SEiBKTBAfBuJ1yI0ShDwKeT1PU2UFD+CA51JY1gEGIq2PRfVvUNHUhi9aMbSXxpLJiNQbAAAaKbg1ppKBm78DLc1xtDSak0QdRXtRKMKypxNqmUWyrlT+MrunD10JCw8sClCHQIRnatjg2AwGqAO6QshA01XzehStId61CojgKud1FJXNqApE3BI1VCQoKMAf4kMlXIgjFGTx2gfJsHdSEZEvLWUGPVV2zYOtt2doQN29wi84AQOkHdIyBRGlwRLNJMA7gL0Th4ZGYDHrBzgTYGAAAYs0OAgqSjvDaGASkC4UEa08KkKMOZygADYwSvBcluGdUc1XzpFbOijy6DBSpbeuuVZ6QOKoHWw9qtGm3SsYwmMDQGWN9tGSeYKlYOM1IcMpBymgACK+ce0YwKLBtodEaiaGSSJJyXGW0FWyJJlQN5ZPKEOhVPth4sooAdZsiTzK1IAUOmO-JxkowGk1csKoWQhD6HHK2PtJRIRIBvU1BofnVBZUC-1Bo-0Gi8s8xMQNvnwypHC8iELYWg23pLFFkskI5Ljli958oCX-PJeC+GULJXMuHrPZZ9sW5ZKbBq7VQk5JISrE-K2K6qgYDnGpVAd6mgrrDGlt+X6s5wMgY60KEI-Wbpkl4p-PAeSECjZhdAalZJGu-wmKkBAE3rosAABwzZYMQAATDNm8ukqg-WRKuHiwk9CpA6wIAA6taGbQg3szdg19k0ZJ4T0g6wYNYM2CY3c9ADOjq7W30QTOp1TgmD0NAc0eLODRnMp3pAO7Rs10vsocHMUSOQhANGlLKCYACKMHEMHIFli5QQtxND2enfxt0TTHPEydfx5Uzg1mR1VaPKN1poy5LTa6cGJwluOVjc6Sgo+xxqMn6kwCvi1V6stNqSzqWaOUAAEsoCAPDjBQAElKDwFhurIvcBbo30ABKqjOkO6ojWp2mkQVW2X8QF0e6p5oJg50UAJA66uVQVAUAzZcIrmUyv+thtjpROIYuYe4L9BiDFHE4h1aBKVT8FIIaZ5KJFccFIpfioL35qcqheyV-6OXp596qjxOfa+2vDhC91SSA1fIrf2-eWPSBikhL++QZ9L3wDEGQgUj4xPsvbfC9k40+UeH7YC9ZYL9UYwQ5JKFdH+3zEEA6LlFgzJOiPf2-qW8MoPXKlcNn8L4kFAi+jrCQ03ftfDhaMcqygWb9LRHBj3iGkGlCCCIg9UsjilUAonWyQCtmEigDCBXWlR00TEgPvmDjJnVDYHQAAB5KQAA+TQEzB4UIT9CkSkB3R2SAicWNILSg8cPgf1ag0lAkA-b8CrLLUfHheUV8AAcT4EQO0w9U0Ft2qEIJl193Y09zQCdwHRJBfQfXKBEObwfUhzq3m3aA52r37AmjQDICjzQGV0UJkjkiQGan0OV2QUwQTQN2v2aFtxNz+zSFQCX3N263sPt2ZBIyyW6zvEuAPT3RKC6yGTp0Zy8LdzrUwxrW91nUw043o3yiEKUPNFfTEMRzY1EykJkM9wx1njV09zyXIinxmAoM-wcHcnJDLB1GxQ3wgC3yImUDgEMjB2pmaGHQt32Q1XihmmgIQKhyQKEPKOkOgMMiIP3QHVMgHQ8XzjEwTwcAEBXBkE-G-FAMnw7ygjmFLjZGzx1GiGQKtxt2NwEjEP0DfWQmtC5B2yyUFE2HhBUSpmt0sFLFcI2kOJ2BgFKjiV2KEJ1TUn1XM2OMbEXnONaH-FZBuNU3uIsAKHcxvHqP+MOHeMD1FC+MKn1zsNeIqhOKBIuNBOuK2AhK0AeIKG1y0AKJNzeI+ORNQCEOPwP3RkxMBLOJxOyDBPxLuMJKhIxjpOskqERM+OpNRJv3pKyUZPdmZKuLZDZNEMhMeIv1wwpKRMfgFN0xfzlABNOLFJBJZLxNuOlI5MeIfw0wVLiVMFhQGUjCLkIEwGIAoFO3wy4AAFY4UDtTsuAABmU7B0j0RkSQTWAiL+aAeANWToIgUgSgWgBgZgdgbgXgQQEQMQD0IAA) I'm editing on.

The page is now blank/white, which indicates an error not being handled correctly.

The console error's the following:
Element.querySelector: '.react-flow__node[data-id="DataCar-source-"""]' is not a valid selector
Uncaught (in promise) 
Object { type: "cancelation", msg: "operation is manually canceled" }

**Comment by 3rd** [comment]
Hey, sorry about that and thanks for opening the issue!
It was caused by the way node ids are used by react-flow, they're interpolated directly into DOM selectors.
I fixed it by replacing double quotes with single quotes inside nodes and deployed the new version, the link should work now.

**Comment by joelsoedito** [comment]
Wow, thanks for the quick fix! Great work on the app btw.

Van: Andrei Neculaesei ***@***.***>
Datum: woensdag, 11 september 2024 om 22:12
Aan: 3rd/tsdiagram ***@***.***>
CC: Joel Soedito ***@***.***>, Author ***@***.***>
Onderwerp: Re: [3rd/tsdiagram] Crash on invalid selector (Issue #18)

Hey, sorry about that and thanks for opening the issue!
It was caused by the way node ids are used by react-flow, they're interpolated directly into DOM selectors.
I fixed it by replacing double quotes with single quotes inside nodes and deployed the new version, the link should work now.
