### ISSUE TITLE
Not an issue, an idea

### ISSUE THREAD

**Issue by carlosonrails** [3rd/tsdiagram#3]
As hard vim user myself, I'd love to use this project with vim navigation keys. What you think about this feature. Maybe a thing that we could activate in the preferences.

**Comment by 3rd** [comment]
Hello, fellow vimmer!
I looked into plugging monaco-vim for a bit but hit this issue: https://github.com/brijeshb42/monaco-vim/issues/117
But it's definitely coming soon!

**Comment by carlosonrails** [comment]
Okay count on me to implement it. I'd love to contribute.

**Comment by 3rd** [comment]
Sounds great, that would be lovely!
I pushed what I had so far on this branch: https://github.com/3rd/tsdiagram/tree/feat/vim-mode
I think everything is working apart from the cursor, but I didn't test it much.

**Comment by carlosonrails** [comment]
Okay. I'm going to fork it and see what I can do.

**Comment by 3rd** [comment]
Handled it on the monaco side, all good now.

**Comment by carlosonrails** [comment]
Oh, great!
