### ISSUE TITLE
Suggestion: Visualize `extends`

### ISSUE THREAD

**Issue by jhoermann** [3rd/tsdiagram#5]
Lets say we have these interfaces:

```ts
interface User {
    id: string
    name: string
}

interface ExtendedUser extends User {
    address: string
}
```

It will result in:
![2023-12-12_13-45](https://github.com/3rd/tsdiagram/assets/13086717/60477378-f526-41de-bf8d-5fe277f44be7)

I'm not quite sure what the optimal visualization would be. Maybe list the original properties too or somehow reference the extended interface. At least there should be a connection.

**Comment by 3rd** [comment]
Added support, ideally we'd have a port for each extended/implemented model, and the parser can support that now, but I'm not sure how to make it not ugly.
Thank you for the issue!

How it works now:
- Members are resolved by the type checker, so we'll always list all of them (fx. A extends Error)
- We display labels in the title for `extends` and `implements` (should work for generics too)
- We draw an edge from the right side of the model title to any nodes it extends or implements.

![diagram (3)](https://github.com/3rd/tsdiagram/assets/59587503/a4fa6aa3-26a0-4670-9522-1128b9071545)

**Comment by 3rd** [comment]
Didn't implement edges for the case where generics are used, see H and G here:
https://tsdiagram.com/#/N4IgJg9gxgrgtgUwHYBcDOIBcBtUBLMLcBAMwEMYAbFEAGhBTxUoSIBFSLq6Q0IYATlFaYQeVAgHlhAAgCCM4AB0kMtTJIQImGWhQDxAcwDcKgL4rxKSdITzFK9TMQDDCMDr0GkJ85YlSZLIAQg6q6gBGZAI6cqZIFkj+1oGyAMJhTmQ6AEoIUBACYAA8Xka08gB88U4ROgCyZAAOxcEVZT6VfkhWNkF2bJnq2fLYALrxicl9sgCiMggAHtZIYGj2yuFqUTG6+kaT06l2AGILy8hr8hWhm7VkAF6e+z6HST0BtjIA4sUAKhUAKqVIZqLw6P41dRIeA6QFvXrHGQACX+5xWVw6hiBMgAvDIYXAIpIQUsMetfgCZMDQTJrHpnt5fAkQGYxvRYAIBMgUGxoPAeQBJQiiMCcKg0MxAA

But will do it soon.

**Comment by jhoermann** [comment]
@3rd Wow that was fast! Great improvement. Your tool is super helpful for team communication!
