### ISSUE TITLE
Suggestion: Visualize optional properties

### ISSUE THREAD

**Issue by daespinogh** [3rd/tsdiagram#6]
It would be great if optional (?) properties were represented in the diagram, it would make it even better for documentation as the required ones would be easy to identify.

**Comment by 3rd** [comment]
Great idea, added!
https://tsdiagram.com/#/N4IgJg9gxgrgtgUwHYBcDOIBcBtUBLMLcBAMwEMYAbFEAGhBTxUoSIBFSLq6Q0IYATlFaYGATwAOCAAQBBaQF5pwADpJpG6SQgRM0tCgF4kAcwDcazdIBGZAQH49AIQtIAvmrXGUCAeWHSTsqWmtq6+obG5iEatg56sq5uIG4AuvSwAgLIKGzQ8DkAkoSiYJxUNG5AA

![diagram (59)](https://github.com/3rd/tsdiagram/assets/59587503/1d507a26-523f-4452-a357-69f2f537b179)
