### ISSUE TITLE
Suggestion: support visualizing discriminated unions.

### ISSUE THREAD

**Issue by matsande** [3rd/tsdiagram#8]
In the following example, it would be really nice if there was a visible connection between `Shape` and `Circle/Square`.

https://tsdiagram.com/#/N4IgJg9gxgrgtgUwHYBcDOIBcBtUBLMLcBAMwEMYAbFEAGhBTxUoSIBFSLq6Q0IYATlFaYQAHVQBPAA4IABAGUAFmVlyAvBLkAfOQGE8Qllt0KAjjDICEAbgkSUM+QaPz1c4FrkBrPEjCYcgDkUIZQLEF2SHJyAmRgeDBogUjwAEYIAlEAvvZSauaW1hoeXr7+gUFoFlYIkV4A7gQoSinpmTl5jgUQiACSKAhwJZ7RcmgqsoHKqrYSuUgg2QC69LAC1qhs0PDIKH2EomCcVDTZQA

**Comment by 3rd** [comment]
Great idea, added, thanks for the issue!
![diagram (4)](https://github.com/3rd/tsdiagram/assets/59587503/a10dc2a8-ea32-40ee-8201-4290a623b08c)
