### ISSUE TITLE
Suggestion: Support namespace

### ISSUE THREAD

**Issue by AlexisVS** [3rd/tsdiagram#9]
Hi, I believe it would be highly beneficial to include support for namespaces in your tools.

In my case, I am using PHP Laravel and employing a package to generate TypeScript types with ValueObjects. The package utilizes my PHP namespaces to create these types.

My file looks like this:

generated.d.ts
```TS
declare namespace App.Application.DataTransfertObjects.MediaLibrary {
    export type ImageAttributesData = {
        src: string;
        srcset: string;
        loadingAttributeValue: string;
        conversion: string;
        width: string;
        height: string;
    };
}
declare namespace App.Application.DataTransfertObjects.Permission {
    export type PermissionData = {
        id?: number;
        uuid?: string;
        name: string;
        description: string | null;
        module: string | null;
        guard_name?: string;
        roles?: Array<App.Application.DataTransfertObjects.Role.RoleData>;
    };
}
declare namespace App.Application.DataTransfertObjects.Profile {
    export type UserProfileImageData = {
        profile_image: any;
    };
    export type UserUpdateProfileData = {
        id: number;
        email?: string;
        password?: string;
        password_confirmation?: string;
    };
}
declare namespace App.Application.DataTransfertObjects.Role {
    export type RoleData = {
        id?: number;
        uuid?: string;
        name: string;
        description: string | null;
        module: string | null;
        guard_name: string;
        permissions?: Array<App.Application.DataTransfertObjects.Permission.PermissionData> | null;
    };
}
declare namespace App.Application.DataTransfertObjects.User {
    export type UserData = {
        id?: number | null;
        uuid?: string | null;
        deleted_at?: any | string | null;
        created_at?: any | string | null;
        updated_at?: any | string | null;
    };
}
declare namespace App.Application.DataTransfertObjects.User.Authentication {
    export type UserLoginEmailData = {
        email: string;
        password: string;
        remember: boolean;
    };
    export type UserLoginTagNumberData = {
        tag_number: string;
    };
    export type UserRegistrationData = {
        gateway_type: string;
        credentials: Array<any>;
        remember_token: boolean;
    };
}
declare namespace App.Application.Services.Frontend.Administration.Action {
    export type ActionData = {
        type: App.Application.Services.Frontend.Administration.Action.ActionTypeEnum;
        properties: { [key: string]: any };
    };
    export type ActionTypeEnum = "link" | "modal" | "custom";
}
declare namespace App.Application.Services.Frontend.Administration.Form {
    export type FormActionTypeEnum = "submit" | "reset" | "custom";
    export type FormActionData = {
        type: App.Application.Services.Frontend.Administration.Form.FormActionTypeEnum;
        label: string;
        parameters: { [key: string]: any };
        class: string;
        color: App.Application.Services.Frontend.Quasar.Shared.Enums.ColorEnum;
    };
    export type FormColumnData = {
        component: App.Application.Services.Frontend.Component.ComponentData;
        class: string;
    };
    export type FormData = {
        url: string;
        inputs: { [key: string]: any };
        visitOptions: App.Application.Services.Frontend.Shared.Inertia.InertiaVisitOptionsData;
        actions: Array<App.Application.Services.Frontend.Component.ComponentData>;
        elements: Array<App.Application.Services.Frontend.Administration.Form.FormRowData>;
        title: string;
        description?: string | null;
    };
    export type FormRowData = {
        columns: Array<App.Application.Services.Frontend.Administration.Form.FormColumnData>;
        class: string;
    };
}
declare namespace App.Application.Services.Frontend.Administration.Page {
    export type PageData = {
        title: string;
        sections: Array<App.Application.Services.Frontend.Administration.Page.Section.SectionData> | null;
        actions: Array<App.Application.Services.Frontend.Administration.Action.ActionData> | null;
    };
}
declare namespace App.Application.Services.Frontend.Administration.Page.Section {
    export type SectionData = {
        components: Array<App.Application.Services.Frontend.Component.ComponentData>;
        title?: string | null;
        subtitle?: string | null;
        description?: string | null;
    };
}
declare namespace App.Application.Services.Frontend.Component {
    export type ComponentCodex = {
        name: string;
        path: string;
    };
    export type ComponentEnum =
        | "ThemeTableTable"
        | "Form"
        | "FormInputText"
        | "FormInputSelect"
        | "FormInputOption"
        | "FormAction";
    export type ComponentData = {
        name: App.Application.Services.Frontend.Component.ComponentEnum;
        properties: { [key: string]: any };
    };
}
declare namespace App.Application.Services.Frontend.Quasar.Actions.Link {
    export type LinkData = {
        label: string;
        endpoint: App.Application.Services.Frontend.Shared.EndpointData;
        color: App.Application.Services.Frontend.Quasar.Shared.Enums.ColorEnum;
        icon?: string | null;
        size: App.Application.Services.Frontend.Quasar.Shared.Enums.SizeEnum;
    };
}
declare namespace App.Application.Services.Frontend.Quasar.Form.Inputs.Option {
    export type InputOptionData = {
        label: string;
        value: any;
        description: string;
    };
    export type InputOptionGroupData = {
        name: string;
        options: Array<App.Application.Services.Frontend.Quasar.Form.Inputs.Option.InputOptionData>;
        type: App.Application.Services.Frontend.Quasar.Form.Inputs.Option.InputOptionTypeEnum;
        inline: boolean;
    };
    export type InputOptionTypeEnum = "radio" | "checkbox" | "toggle";
}
declare namespace App.Application.Services.Frontend.Quasar.Form.Inputs.Select {
    export type InputSelectData = {
        name: string;
        label: string;
        description: string;
        default: string;
        multiple: boolean;
    };
}
declare namespace App.Application.Services.Frontend.Quasar.Form.Inputs.Text {
    export type InputTextMaskEnum =
        | "date"
        | "datetime"
        | "time"
        | "fulltime"
        | "phone"
        | "card";
    export type InputTextTypeEnum =
        | "text"
        | "password"
        | "textarea"
        | "email"
        | "search"
        | "tel"
        | "file"
        | "number"
        | "url"
        | "time"
        | "date";
    export type InputTextData = {
        name: string;
        type: App.Application.Services.Frontend.Quasar.Form.Inputs.Text.InputTextTypeEnum;
        label: string;
        description: string;
        canGrow: boolean;
        mask?: App.Application.Services.Frontend.Quasar.Form.Inputs.Text.InputTextMaskEnum | null;
    };
}
declare namespace App.Application.Services.Frontend.Quasar.Shared.Enums {
    export type ColorEnum =
        | "primary"
        | "secondary"
        | "accent"
        | "dark"
        | "positive"
        | "negative"
        | "info"
        | "warning";
    export type SizeEnum = "xs" | "sm" | "md" | "lg" | "xl";
}
declare namespace App.Application.Services.Frontend.Quasar.Table {
    export type QTableColumnAlignEnum = "left" | "right" | "center";
    export type QTableColumnData = {
        name: string;
        label: string;
        field: string;
        sortable?: boolean;
        align: App.Application.Services.Frontend.Quasar.Table.QTableColumnAlignEnum;
        required?: boolean;
    };
    export type QTableData = {
        uniqueKey: string;
        title: string;
        columns: Array<App.Application.Services.Frontend.Quasar.Table.QTableColumnData>;
        rows: Array<{ [key: string]: any }>;
        showable: boolean;
        showableEndpoint: string | null;
        actions?: Array<App.Application.Services.Frontend.Administration.Action.ActionData> | null;
    };
}
declare namespace App.Application.Services.Frontend.Shared {
    export type EndpointData = {
        httpMethod: App.Application.Services.Frontend.Shared.Enums.HttpMethodEnum;
        endpoint: string;
        parameters: { [key: string]: string };
        external: boolean;
    };
}
declare namespace App.Application.Services.Frontend.Shared.Enums {
    export type HttpMethodEnum = "get" | "post" | "put" | "patch" | "delete";
}
declare namespace App.Application.Services.Frontend.Shared.Inertia {
    export type InertiaVisitOptionsData = {
        method: App.Application.Services.Frontend.Shared.Enums.HttpMethodEnum;
        replace: boolean;
        preserveState: boolean;
        preserveScroll: boolean;
        only: Array<string>;
        errorBag: string | null;
        forceFormData: boolean;
    };
}
```

**Comment by 3rd** [comment]
Thanks for the issue, your super long code uncovered some performance issues and allowed me to fix that!
Added support for modules and namespaces: [Demo](https://tsdiagram.com/#/N4IgJg9gxgrgtgUwHYBcDOIBcBtUBLMLcBAMwEMYAbFEAGhBTxUoSIBFSLq6Q0IYATlFaZiUSmQEIABEjKI0ABzLDpAQUWKAdBsWU8UMowhItbI2QAqAskjQkEAlAHkARgCsEUdFoCyCMDwyABk8VxsBAE9pYAAdJGlE6QQAD0UIJ2kUSMUZAEk4MgBzBDUUFAEwmBQENHMUMmkAXhj4pPbpNCFMToq8JCKAbjaOxK6oNAQUHrQ+geGE0elKCDJAgbK+12qEADUyShgEGbmhkdGoEwA3RzQ8ExPK+fOOgHcCFAALR-6zxdHPgg8EVPtNek8-u0AL4LKHxMBeCRSWTyWrKVS6HSafSGYymepWGx2BxONyebxoLQABUccDwaDuJla-2SaQyKCyORkNIEdIZ9yQBOazKW0gIAH4ekh4K5HAtRTAYBKfs8We05IgVZClgi0FBKoo8VrpAAfWRUSjypZwCBgKjHcG-U3myiWl7tIowSRgAD6GoQksdqtFAggLDQgbUAhskQAPJjdDijAKzBZrLZ7I4XB4vD4AEphhBaAssAkAPitiRh8ThSAR4kkMn9ShUMgT2IMyZMqYa6eJWbJucpVNDJDwLBFSVS6Uy2Vy0gAqpMBCOIGOWAVigghS04mqkopR+OED68IUSj1bJFK9Jqyzp+zOfOl44F4owEYEKv19uLMK96KBBSjKcrulOhTjoGswQje7TKAyrwZGAUGnLBB5kAhSE+pcSBjryXZIChMEvHetb1kiTaoi2GKaFieidniPaEhmJLZuS+aFpOiQPrOXLSCWv4NP+YGJMq5pwLKAhoYkipidBvzSSimpBtqoy6vqeCGgKxpmtKrqKTadosDpLpuvuiSet6fqolqim5Ly9KMnYkbRmQcbtvRuIpgSfaZqSOYUtStKOSmPJ8k55bOnpZnQrC8KIo2Sloq26i0YmDHeWmRJ+WxQ5aC+AhcayM4cnOMgFTuRXtGJ0oSY4UUWopsnISZ0WKQiLA1L6RiBlezryQMDX6SJ0j6ggn7dSgvVINEZoDUUQ0xUsMDvhNPo9ZeM39aci03qR8UNsizbom2aUdl53Y+dlrGDoFBU6NUgKoBlTIAVObK8c+y7BBART9AAohBlCVW9owIEDtkjfBaCIQIYCQ+Z0hSIgdUCD0rgQIWth7TePGlXxBU-X9SCWMUAByIECCDI0NEUfqUwjsUvHjT7lcueYIH90EEdTiNFJ+rxuT6ZWM0sY0Is9BxoD0UYxrGV4ViNyPg5JwsQAA1sg6OYyw2MkXFdYJUdVEnal2jpRdpgAMqOFcBi1FoABioaoMgYA6GAdJIPSFQETo3gCkVLNleoAcmLzooi2bdFJoxNsCHbwiUs7Jg1HWHtez7NiMWoYemLneKWFy-21XZob2YwtQ9MA0jYJrkRagAupt0R3kz94ffj84FwKRe5CX8DCrEID6Eg6vD86w+GQcE9msPsCzBAcDDwb5GJcdKUebHKbx4nDsp676dqJ7-RZ37jsZHAQed6z0gX7yPcmH3CAD1fLTD2gMCuHSKCz9Iw9SEmL-EAk8QALxQEvFezMb4h3vnAR+go-y7hplyGWZ1PJ+13vbZOLs07u2PpnbmjE4FO0vgg5+r9FISFlJQUWoxlA2EQDUAQ0sYi13rk3Fut5FINgZHQjolwVho2jhbTBttsFO1wW7LQABFL0aBJBaCtp8Rs7tX6UgAMJhgyJQ-W0CSq3zgVow4cBEFCWQYjS4cB0hIGQGCLeL1rbiKTpI1O0itHWJMHYrQHibF2IJDwiQfCVI430Y+WBl8I7LQELQkJI1+iKGqKwmudcEANxUs3aQfU25LDtncFwWkTCsIcZbJRzj95SPTso1RWg8i2KcEEWp9TGBkF2PSJgzhCl2ACSNFQeJimuXcug7e3YsEuIPngnxS8-GoCmZ42xqByyKQQCwRAqABlyxKWIhOEiJnSIIafIhKYSFwILK8JZNMmDGTiYjdSBo8RESdLpRqeiO4GIibyM5USLhhngHYGWgz4zDMcWUnZ4zKn4JPt7I53YTmX2MX8i5ligmsPmqEpAZEjaUQUKbLZcdyk4LcUfKFZ9GJUi3Nfd5fFyUlG+R0RgzAHRopGpMPOGy3JAvNudbZe9CWH0hYQ32ZKtxlLzqKvEkVnnDURn0gU7KhlcowfisFFSiUCsOUKlMCD-YSosGWXarzMWHWxclGiiqRlOJVXyyZBzoWau7DSosNs86UvCXxZ1urzFVSSFYmZ6AAWbOBaUsZqr+VzL9eGrxiy9WKQZSwR5g0pVLVGJ-VwcaAytRebc2oGkukJoWkm9FRqKJJWoqdc1IKQ3WvcdMqNHJQbFTdfOXxdatEIhSMJRG-p+FwSMN8G57d2jBz4i2hZKBX7NBGnPEAlhASIFJq4FgC6WDDynf-EAcDV2I2nXAupiSUCWFSMAtdw9d1IH3TbFg3gt2ih3ZfPd1ROl4hvUsO9D885QLeU2mQo7-FIO9YkbtIjuXKt5a4sNv7ZmQfHaXKG5csx4Crmw1J6T5qZOyUWg6JaN5mpjpWgl4HJlyIwoohBlJQhj1dZ9GQFH1Z0vaNQlZPapx1nSP0exQaeW7IhUolRUg1GsYgOxnpljtHCLxTvAjez07EYUQIXjNT1FTKEboxGBgTD5oNYjO4AAvB0EnRlSZ47JxR1T+NaCU1bPAenVPt2LevE2m9OOge42q2R8jFEkIfT4J9gcG3DvnN53z4d-0NoY2QGhzHEhXAOEcFu7Uc33O0gOpIOTuIwL4kFrpABxUMK16NJCA8yxGEAunys5Xh4NRm3Mmfk1589SStDBdMFlz1ZBFaIyjgZy1YHpPu1q6Q3kTT92Uma8Nx9XSKGwbU0gUeDoMZYyQOiodGXAsNYKYXYutUh4gBsIECAf956AigOrDGKRDsMF+kUFdIBV5YtLbi5zkmrWEekQN+rI2ylXvrWE6j0hvOXtzAVwDNkUujEY7E4roo7maSNGDjoCJyBUDBFD60yPNLXIW7rJbhqsMOZxU5itVWXt9fcyRurl9xs+EPSkH7X6-veZpygXwGF1YTqaCe8An4X2jGnR+GojBEA846NOwXCBhftGnSQC0YuJdJGnYoT4Xi5eJGnYYOGn6VtUrW-upnU3B4c+3eumotOVegOhrDMAZvRdHsbGQa367wZkHHA7j+40hCfFdwwFZXufxe9qpJL3ghKBe9lyATn-Pxe3d+13fI62mfA6SlF1maCidcfBTVjzFOhvecpEzqneutvwCoRFpj8P2gw66cnwwSBcsQFeNrRbBlWeRie4Zknxms+DbgFTvPR6C9HpZ2gNn23C248Nsah7hPKvp9DURrvZmAgWdqmgKjsfpDGJ0dtw3t712HjPJISIXvWUmA-FEL3KhhCoC92f8e4ejfD3SPkvANx-ec2TK-+-u-h79BIAdr-r666gsAg3sAwmu702uMgVmNm2+66KQaAF2aAy8IC06cAVuKB66lARQF2KQIe0eGKeOxsBOuGoiLmGeYaA2y6Mg-mq2MgMiVBCKpiag+gRQSA7OmBpAwCoClQIIXBaudijg4B6WkB0g9BEWLAjBZijQFiooRWqEI0EOyeY4Ky8M5eSQfATg4hGa0gWO40OOMqLBSAqeM+ZBc+b2XeVBsiDBvyTBhhtmSwUgAAjkqPxoGLoXrCyGlo2n9mIYuoJNIQBtIDAN7M4QgAANJpLJ7prV42H-LqCArdagq9ad7k5aCWG+ESGxFIohj17lYpIcIZJcJQgdaihoBK6Cx+GN7Y6KRlH15aElxgBsaoCZrSqiiypFIuSBpp6mHVrEqCrZxapioIKSqmSYYT7YaOYkEgbPbJFuaL5gBr63wNFNEoCJ6ggoCKD+BfC2jGGkEzGuZhrzHL7wCUgAAS5QmxUwSuYA9hYMgm7GyeDCqIzCyS7CkRhRKk3CI0R6jgcgsS7h+hdmhBJqZawGSq+x5BkyRx6iixIc5xGxWx1x7Bw8JQfBe+EAswF2+6WJRgUAnuGBw8HUUwUed2k+OG5aJhEJZhVSfGS+dSCGjQNBIh9JDSrS7SG2cqieTC1xux0x7esxhxtJAmJxWg8Jlx2xNx02IYCAegrYVRehZctQtsCAVsDQNQ8pHhooh4SpCcKp+oYY-xOsCpI0JglA6SssHK80JRSwjgoYAgAAQsUC0cmh0H-kIAgHAgSBqYCalrCCAFCI3PQLANGP4tAPAHYnkIQKIIjlwDQFCEAA)

**Comment by AlexisVS** [comment]
Great. thanks a lot 😄
